# Mqtt Configuration
[MQTT]
ip = "127.0.0.1"                    # Mqtt Ip
port = "1883"                       # Mqtt Port
error_file = "mqtt_error.log"       # Error Log file
critical_file = "mqtt_critical.log" # Criti Log file
warn_file = "mqtt_warn.log"         # Warn Log file
debug_file = "mqtt_debug.log"       # Debug Log file

[LOG]
level = "TRACE"      # "TRACE", "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"
filename = "app.log" # Log file name
